name = 'pydon'
#name = 'Madonna'
#name = 'Donner'
#name = 'MasterDon'
#since = '2021-08-12T00:00:00+0900'
created_at = '2021-08-12T00:00:00+0900'
url = 'https://github.com/ytyaru/Python.Mastodon.Api.Toot.20210813105938'
[requirements]
    [language]
    name = 'python'
    version = '3.7.3'
    [sdk]
    name = 'python'
    version = '3.7.3'
    [[packages]]
    name = 'requests'
#    version = ''
