name = 'ytyaru'
#email = ''
[user]
github.com = 'ytyaru'
twitter.com = 'ytyaru1'
profile.hatena.ne.jp = 'ytyaru'
mstdn.jp = 'ytyaru'
#url = 'https://github.com/ytyaru'
#https://twitter.com/ytyaru1
#https://profile.hatena.ne.jp/ytyaru/
#https://mstdn.jp/@ytyaru
